image: jochym/dockers:nbdev

# Cache modules in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG

clean:
  stage: build
  script:
    - ls -lR 
    - git config --global --add safe.directory /builds/jochym/hecss
    - echo "Check we are starting with clean git checkout"
    - if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
    - echo "Trying to strip out notebooks"
    - nbdev_clean
    - echo "Check that strip out was unnecessary"
    - git status -s # display the status to see which nbs need cleaning up
    - if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"; false; fi

test:
  stage: test
  script:
    - echo "Running test with flags:" $NBDEV_TEST_FLAGS
    - nbdev_install
    - nbdev_test --do_print --flags $NBDEV_TEST_FLAGS
    - hecss_sampler --help
    - calculate_xscale --help
    - plot_stats --help
    - plot_bands --help

# pages:
#   stage: deploy
#   script:
#     - |
#         if [ .$BUILD_DOCS != '.yes' ]; then 
#           echo "Not building docs"
#         else 
#           echo "Building docs..."
#           nbdev_install
#           nbdev_docs
#           cp -r _docs/ public/
#         fi
#   artifacts:
#     paths:
#       - public
