project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]

quartodoc:
  style: pkgdown
  package: hecss
  version: 0.5.29
  dir: reference
  title: Function reference
  source_dir: "."
  parser: google
  sections:
    - kind: section
      title: Core
      contents:
        - kind: auto
          name: HECSS