name: hecss-dev
channels:
  - conda-forge
  - fastai
dependencies:
  - python=3.10
  - pip
  - setuptools
  # Core Library Dependencies
  - fastcore>=1.5
  - numpy
  - scipy
  - ase
  - spglib
  - tqdm
  - click
  - matplotlib
  - ipython
  # Domain Specific
  - alamode
  - openkim-models=2021.01.28
  - asap3
  # Development Tools
  - nbdev
  - jupyterlab
  - ipywidgets
  - pre-commit
  - quarto
  - pip:
    - -e .
