[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hecss"
version = "0.5.29"
description = "High Efficiency Configuration Space Sampler"
readme = "README.md"
authors = [
    {name = "Paweł T. Jochym", email = "pawel.jochym@ifj.edu.pl"}
]
license = {text = "GPL-3.0-or-later"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
keywords = ["physics"]
requires-python = ">=3.9"
dependencies = [
    "fastcore>=1.5",
    "numpy",
    "scipy",
    "ase",
    "spglib",
    "tqdm",
    "click",
    "matplotlib",
    "ipython",
    "marimo>=0.17.6",
]

[project.scripts]
hecss_sampler = "hecss.cli:hecss_sampler"
plot_stats = "hecss.cli:plot_stats"
plot_bands = "hecss.cli:plot_bands"
calculate_xscale = "hecss.cli:calculate_xscale"
reshape_sample = "hecss.cli:reshape_sample"

[project.optional-dependencies]
dev = [
    "pytest",
    "marimo",
    "quartodoc",
    "quarto-cli",
    "jupytext",
    "nbconvert",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["hecss*"]

[tool.setuptools.package-dir]
"hecss" = "hecss"

[tool.pytest.ini_options]
testpaths = ["notebooks"]
python_files = ["*.py"]
python_functions = ["test_*"]

[tool.marimo]
notebook_dir = "notebooks"

[tool.build_lib]
init_star_import = "core"
