# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"normalize_conf": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "//hecss/"

git_url = "https://gitlab.com/jochym/hecss/tree/nbdev/"

def custom_doc_links(name): return None
