"""Generated from notebooks/optimize.py by build_package.py"""

from __future__ import annotations

import sys
import pathlib
import itertools
from fastcore.basics import patch
import numpy as np
from numpy import log, exp, sqrt, linspace, dot
import scipy
from scipy import stats
from scipy.special import expit
from tqdm.auto import tqdm
from itertools import islice
from collections import Counter
from matplotlib import pyplot as plt
import ase
import ase.units as un
from ase.calculators import calculator
from ase.data import chemical_symbols
from ase import Atoms
import spglib
from spglib import find_primitive, get_symmetry_dataset

def get_sample_weights(data, T, sigma_scale=1.0, border=False, debug=False):
        """
        Generate data weights making the probability distribution of `data` in 
        sample format into normal distribution corresponding to temperature `T`.
        The actual distribution traces the normal curve. Normally, no weight 
        is given to the data outside the input data range. This may skew the 
        resulting distribution and shift its parameters but avoids nasty border
        artefacts in the form of large weights given to border samples to account 
        for the rest of the domain. You can switch this behavior on by passing 
        `border` parameter (not recommended).

        #### Input
        * `data`        - list of samples generated by HECSS sampler ([n, i, x, f, e])
        * `T`           - temperature in kelvin
        * `sigma_scale` - scaling factor for variance. Defaults to 1.0.
        * `border`      - make border samples account for unrepresented part of domain
        * `debug`       - plot diagnostic plots

        #### Output (weights, index)
        * weights     - array of weights in sorted energy order
        * index       - indexing array which sorts samples by energy

        """
        assert len(data) >= 2
        nat = data[0][2].shape[0]
        mu = 3 * T * un.kB / 2
        sigma = np.sqrt(3 / 2) * un.kB * T / np.sqrt(nat)
        g = stats.norm(mu, sigma_scale * sigma)
        e = np.fromiter((s[-1] for s in data), float)
        idx = np.argsort(e)  # You can use slightly (10%) wider sigma to compensate 
        ridx = np.arange(len(idx))[idx]  # for the missing tails below weight=1
        d = e[idx]
        if debug:
            N_bins = max(len(data) // 20, 20)
            data_range = 4 * sigma
            plt.hist(d, range=(mu - data_range, mu + data_range), bins=N_bins, histtype='step', density=True, alpha=0.75, label='Input histogram')
            plt.plot(d, -0.05 * g.pdf(mu) * np.ones(d.shape), '|', alpha=max(0.01, min(1.0, 100 / len(d))))
            plt.axhline(lw=1, ls=':')
        bb = np.zeros(len(d) + 1)
        bb[1:-1] = (d[:-1] + d[1:]) / 2
        bb[0] = d[0] - (d[1] - d[0]) / 2
        bb[-1] = d[-1] + (d[-1] - d[-2]) / 2
        bw = bb[1:] - bb[:-1]
        cdf = g.cdf(bb)
        if border:
            cdf[0] = 0
            cdf[-1] = 1
        w = cdf[1:] - cdf[:-1]
        w = w / w.sum()
        if debug:
            plt.stairs(w / bw, bb, fill=False, lw=1, label='Weighted samples')  # bin widths
            x = np.linspace(mu - data_range, mu + data_range, 100)
            plt.plot(x, g.pdf(x) / (cdf[-1] - cdf[0]), '-', label='Target')
            plt.hist(d, weights=w, range=(mu - data_range, mu + data_range), bins=N_bins, density=True, alpha=0.3, label='Weighted histogram')
            plt.xlim(mu - data_range, mu + data_range)
            plt.legend(loc='upper right', bbox_to_anchor=(1.0, 1.0))  # make border sample account for the rest of the domain
            plt.show()
        return (w, idx)

def make_sampling(data, T, sigma_scale=1.0, border=False, probTH=0.25, Nmul=4, N=None, nonzero_w=True, debug=False):
        """
        Generate new sample with normal energy probability distribution
        corresponding to temperature `T` and size of the system inferred 
        from data. The output is generated by multiplying samples 
        proportionally to the wegihts generated by `get_sample_weights`
        and assuming the final dataset will be `Nmul` times longer 
        (or the length `N` which takes precedence). If `nonzero_w` is `True`
        the data multiplyers in the range (probTH, 1) will be clamped to 1,
        to avoid losing low-probability data. This will obviously deform the
        distribution but may be beneficial for the interaction model constructed
        from the data. The data on output will be ordered in increasing energy
        and re-numbered. The configuration index is retained.

        #### Input
        * `data`        - list of samples generated by HECSS sampler ([n, i, x, f, e])
        * `T`           - temperature in kelvin
        * `sigma_scale` - scaling factor for variance. Defaults to 1.0.
        * `border`      - make border samples account for unrepresented part of domain
        * `probTH`      - threshold for probability (N*weight) clamping.
        * `Nmul`        - data multiplication factor. The lenght of output data will be
                          approximately `Nmul*len(data)`.
        * `N`           - approximate output data length. Takes precedence over `Nmul`
        * `nonzero_w`   - prevent zero weights for data with weights in (probTH, 1) range
        * `debug`       - plot diagnostic plots

        #### Output
        Weighted, sorted by energy and re-numbered samples as a new list. 
        The data in the list is just reference-duplicated, not copied.
        Thus the data elements should not be modified.
        The format is the same as the data produced by `HECSS` sampler.

        """
        if len(data) < 2:
            print('WARNING: You need at least 2 samples to generate waighted sampling.')
            print('Returning unchanged data')
            return data
        if N is None:
            N = int(Nmul * len(data))
        if Nmul > 25:
            print('Warning: You cannot generate data from thin air.\nNmul above 25 is pointless. Doing it anyway.')
        nat = data[0][2].shape[0]
        mu = 3 * T * un.kB / 2
        sigma = np.sqrt(3 / 2) * un.kB * T / np.sqrt(nat)
        w, idx = get_sample_weights(data, T, sigma_scale=sigma_scale, border=border, debug=debug)
        iw = N * w
        if nonzero_w:
            iw[np.logical_and(probTH < iw, iw < 1)] = 1
        iw = np.rint(iw)
        wd = []
        iwnorm = iw.sum()
        for ww, ii in zip(iw, idx):
            if ww < 1:  # Block zero weights in the +/- 3*sigma zone to not lose data
                continue  # iw = np.round(w*nf) + (1*(np.abs(d - mu) < 3*sigma))
            wd = wd + int(ww) * [data[ii]]
        wd = [(n,) + d[1:] for n, d in enumerate(wd)]
        if debug:  # Don't remove low probability data, rise weights above probTH
            N_bins = max(len(data) // 20, 20)  # This will deform (rise) the wings of the histogram
            data_range = 4 * sigma
            e = np.fromiter((data[i][-1] for i in idx), float)
            plt.hist(e, weights=w, range=(mu - data_range, mu + data_range), bins=N_bins, density=True, alpha=0.3, label='Float weights')
            wde = np.fromiter((s[-1] for s in wd), float)  # Weight the data by multiplication of data points
            plt.hist(wde, range=(mu - data_range, mu + data_range), histtype='step', bins=N_bins, density=True, alpha=0.75, label='Integer weights')  # The output will be in energy order!
            x = np.linspace(mu - data_range, mu + data_range, 300)
            fit = stats.norm.fit(wde)
            plt.plot(x, stats.norm.pdf(x, mu, sigma), '--', label=f'$\\mu$={2 * mu / 3 / un.kB:.1f}; $\\sigma$={2 * sigma / 3 / un.kB:.1f} (Target)')
            plt.plot(x, stats.norm.pdf(x, *fit), label=f'$\\mu$={2 * fit[0] / 3 / un.kB:.1f}; $\\sigma$={2 * fit[1] / 3 / un.kB:.1f} (Fit)')
            plt.title('Generated weighted sample')
            skip = len(data) // 2000
            skip = int(max(1, skip))  # renumber the samples
            mh = stats.norm.pdf(mu, mu, sigma)
            plt.plot(e[::skip], -0.05 * mh * np.ones(e[::skip].shape), '|', color='C1', alpha=max(0.01, min(1.0, 100 / len(e))))
            plt.axhline(lw=1, ls=':')
            plt.xlim(mu - data_range, mu + data_range)
            plt.legend(loc='upper right', bbox_to_anchor=(1.0, 1.0))
        return wd

def refit(data, mu, sigma, sigma_scale=1.0, probTH=0.25, Nmul=4, N=None, Nb=None, target=stats.norm):
        """
        Re-shaper of the data distribution.
        This is internal function used for experimentation.
        """
        if N is None:
            N = Nmul * len(data)  # Data multiplication factor
        g = target(mu, sigma_scale * sigma)
        d = np.sort(data)
        bb = np.zeros(len(d) + 1)
        bb[1:-1] = (d[:-1] + d[1:]) / 2  # Target distribution
        bb[0] = d[0] - (d[1] - d[0]) / 2  # You can use slightly (5% for N=10*len(data)) smaller sigma 
        bb[-1] = d[-1] + (d[-1] - d[-2]) / 2  # to compensate for the missing tails below weight=1
        bw = bb[1:] - bb[:-1]
        cdf = g.cdf(bb)
        w = cdf[1:] - cdf[:-1]
        w = w / w.sum()  # Make bins for PDF evaluation
        nf = N  # Each data point gets its own bin by splitting 
        iw = nf * w  # the distance between data points in half.
        iw[np.logical_and(probTH < iw, iw < 1)] = 1  # The boundary points get symmetrical bins.
        iw = np.round(iw)
        wd = list(flatten([int(ww) * [dd] for ww, dd in zip(iw, d) if ww >= 1]))
        if Nb is None:
            Nb = min(len(data) // 4, 15)
        h, b, _ = plt.hist(wd, bins=Nb, density=True, alpha=0.3)  # bin widths
        x = np.linspace(mu - 3 * sigma, mu + 3 * sigma, 300)
        fit = target.fit(wd)
        plt.plot(x, target.pdf(x, mu, sigma), '--', label=f'$\\mu$={mu:.1f} $\\sigma$={sigma:.1f} (Target)')
        plt.plot(x, target.pdf(x, *fit), label=f'$\\mu$={fit[0]:.1f} $\\sigma$={fit[1]:.1f} (Fit)')
        skip = len(d) // 2000
        skip = int(max(1, skip))  # Data weights to fit the target distribution
        nf = iw[::skip].max()  # w = g.pdf(bp)*bw
        for s, a in zip(d[::skip], iw[::skip]):
            if a < 0.001:
                continue
            plt.axvline(s, ymin=0.97, ymax=0.99, ls='-', color='r', alpha=np.sqrt(a / nf))  # Block zero weights in the +/- 3*sigma zone to not lose data
        return (w, iw, wd)

__all__ = ["make_sampling", "get_sample_weights", "refit"]