"""Module docstring"""

# AUTOGENERATED! DO NOT EDIT!

__all__ = ['plan_T_scan']

import itertools
from matplotlib import pylab as plt
from scipy import stats
import ase.units as un
import numpy as np
from ase.build import bulk
from hecss.core import HECSS
from hecss.monitor import plot_stats
from hecss.optimize import make_sampling
from hecss.util import select_asap_model, create_asap_calculator
from tqdm.auto import tqdm

flatten = itertools.chain.from_iterable

def plan_T_scan(Tlo, Thi, nat, N=1, plot_dist=True):
    l = Tlo
    n = np.sqrt(3 * nat / 2 / 2)  # 1/sqrt(2) adjusts for the shape of the distribution 
    s0 = l / n  # generated by the HECSS.smple function.
    s = s0
    assert n > 1
    a = (n + 1) / (n - 1)
    r = []
    while l <= Thi:
        sf = s
        if l * a > Thi:
            sf = sf * 1.12
        r.append([l, s, sf / s0])
        l = l * a
        s = l / n
    ns = 1
    frm = 'N=%.1f'
    if N > 1:
        ns = N / r[-1][-1]
        frm = 'N=%.0f'
        r = [[l, s, int(round(ns * sf))] for l, s, sf in r]
    frm = frm + ' T=%.0fK'
    if plot_dist:
        f = stats.norm.pdf
        x = np.linspace(Tlo * (1 - 3 / n), Thi * (1 + 3 / n), 600)
        y = np.zeros(x.shape)
        for c, (l, s, sf) in enumerate(r):
            p = sf * f(x, l, s)
            plt.plot(x, p, label=frm % (sf, l))
            y = y + p
        plt.plot(x, y)
        plt.legend(loc='upper right')
        plt.xlabel('Temperature')
        plt.ylabel('Relative density')
        plt.title('Temperature scan. N=relative number of samples')
    return r

N_1 = 1000
plt.figure(figsize=(10, 6))
plan_1 = plan_T_scan(150, 250, len(cryst), N_1)

smpls = {}
for T, sig, n_1 in tqdm(plan_1):
    smpls[T] = np.array([s[-1] for s in hecss._sampler_ser(T, n_1)])

ell = np.concatenate(list(smpls.values()))
e_min = ell.min()
e_max = ell.max()

for T_1, el_1 in smpls.items():
    plt.hist(el_1, bins=50, histtype='step', label=f'T={T_1:.0f}K', range=(e_min, e_max))
plt.hist(ell, bins=50, stacked=True, color='C0', alpha=0.25, range=(e_min, e_max))
plt.legend()

plt.figure(figsize=(10, 6))
if N_1 < 10000:
    bins_1 = np.linspace(e_min, e_max, 50) * 2 / un.kB / 3
else:
    bins_1 = 'auto'
cnt, bins_1, _ = plt.hist(ell * 2 / un.kB / 3, bins=bins_1, density=False, alpha=0.6, label='Total')
x = np.linspace(bins_1[0], bins_1[-1], 300)
y = np.zeros(x.shape)
tdx = bins_1[1] - bins_1[0]
for c_1, ((T_2, el_2), (Tp, sig_1, n_2)) in enumerate(zip(smpls.items(), plan_1)):
    e = el_2 * 2 / un.kB / 3
    Tc, Tb, _ = plt.hist(e, bins=bins_1, density=False, histtype='step', color=f'C{c_1 + 1}')
    dx = Tb[1] - Tb[0]
    fit = stats.norm.fit(e)
    plt.plot(x, dx * n_2 * stats.norm.pdf(x, *fit), color=f'C{c_1 + 1}', label=f'T={T_2:.1f}K (N={int(Tc.sum())})')
    y = y + tdx * n_2 * stats.norm.pdf(x, *fit)
    skip_1 = len(el_2) // 500
    skip_1 = max(1, skip_1)
    for v in e[::skip_1]:
        plt.axvline(v, ymin=0.95, ymax=0.98, ls='-', color='r', alpha=0.05)
plt.plot(x, y, '--', label='Total')
plt.xlabel('Temperature (K)')
plt.legend(loc='upper right')
plt.title('Temperature scan - HECSS generated energies.')
plt.grid()
plt.savefig(f'AUX/T_scan_N={N_1!r}.pdf')

N_2 = 1000
plt.figure(figsize=(8, 4))
plan_2 = plan_T_scan(200, 400, len(cryst), N_2)
plt.savefig('AUX/T_scan_plan.pdf', bbox_inches='tight')

smpll = []
for T_3, sig_2, n_3 in tqdm(plan_2):
    smpll.append([s for s in hecss.sample(T_3, n_3)])
ell_1 = [[s[-1] for s in sl] for sl in smpll]

usmp = []
for sl in smpll:
    usmp = usmp + sl

plt.figure(figsize=(8, 4))
plt.hist([s[-1] for s in usmp], bins='auto', density=True)
plt.xlabel('Potential energy (meV/at)')
plt.ylabel('Probability density (meV/at)$^{-1}$')
plt.title('Temperatures: 200-400K')
plt.savefig(f'AUX/uniform.pdf', bbox_inches='tight')

T_4 = 273
wd = make_sampling(usmp, T_4, N=4 * N_2, nonzero_w=False, debug=True)
print(len(usmp), len(wd))
plt.legend(loc='upper right', bbox_to_anchor=(1.0, 0.95))
plt.show()
plot_stats(wd, T_4, sqrN=True, show=False)
plt.savefig(f'AUX/T_scan_T={T_4:.0f}K.pdf', bbox_inches='tight')

plt.figure(figsize=(10, 6))
if N_2 < 1000:
    bins_2 = np.linspace(min(flatten(ell_1)), max(flatten(ell_1)), 40) * 2 / un.kB / 3
else:
    bins_2 = 'auto'
cnt_1, bins_2, _ = plt.hist(np.array(list(flatten(ell_1))) * 2 / un.kB / 3, bins=50, density=False, alpha=0.3, label='Total')
x_1 = np.linspace(bins_2[0], bins_2[-1], 300)
y_1 = np.zeros(x_1.shape)
tdx_1 = bins_2[1] - bins_2[0]
for c_2, (el_3, (T_5, sig_3, n_4)) in enumerate(zip(ell_1, plan_2)):
    e_1 = np.array(el_3)
    bins_2 = 'auto'
    Tc_1, Tb_1, _ = plt.hist(e_1 * 2 / un.kB / 3, bins=bins_2, density=False, histtype='step', color=f'C{c_2 + 1}')
    dx_1 = Tb_1[1] - Tb_1[0]
    nf = np.sum(Tc_1) * dx_1
    fit_1 = stats.logistic.fit(e_1 * 2 / un.kB / 3)
    plt.plot(x_1, nf * stats.logistic.pdf(x_1, *fit_1), color=f'C{c_2 + 1}', label=f'T={T_5:.1f}K (N={int(Tc_1.sum())})')
    y_1 = y_1 + nf * stats.logistic.pdf(x_1, *fit_1)
    skip_2 = len(el_3) // 1000
    skip_2 = max(1, skip_2)
    for v_1 in e_1[::skip_2] * 2 / un.kB / 3:
        plt.axvline(v_1, ymin=0.95, ymax=0.98, ls='-', color='r', alpha=0.05)
plt.plot(x_1, y_1, '--', label='Plan (total)')
plt.xlabel('Temperature (K)')
plt.legend(loc='upper right')
plt.title('Temperature scan - HECSS generated energies.')
plt.grid()
plt.savefig(f'AUX/T_scan_N={N_2!r}.pdf')
