"""This module provides a way to extract amplitude correction matrix from the eta calculation data generated by the `estimate_width_scale` method."""

# AUTOGENERATED! DO NOT EDIT!

__all__ = ['plot_virial_stat']

from glob import glob
from hecss import HECSS
from matplotlib import pyplot as plt
from spglib import find_primitive, get_symmetry_dataset
import ase
import ase.units as un
import numpy as np
import spglib
from ase.calculators.vasp import Vasp
from hecss.monitor import plot_hist
from hecss.util import normalize_conf, get_cell_data
from scipy.special import expit
from scipy.stats import chi2, chi, norm

def plot_virial_stat(cryst, smpl, normal=True):
    elems = cryst.get_chemical_symbols()
    elmap = cryst.get_atomic_numbers()
    vir = np.array([abs(s[2] * s[3]) for s in smpl])
    vir /= vir.mean(axis=(-1, -2))[:, None, None]
    nat = len(elems)
    xscale = np.ones(cryst.get_positions().shape)
    mi = 1
    ma = 1  # m, s = plot_hist(vir.mean(axis=(-1,-2)), 'Total', 0, normal=True)
    for n, el in enumerate(sorted(set(elems))):
        elmask = np.array(elems) == el
        m, s = plot_hist(1 / np.sqrt(vir[:, elmask, :].mean(axis=(-1, -2))), el, n + 1, normal=normal, df=3 * sum(elmask))
        if mi > m - 3 * s:
            mi = m - 3 * s
        if ma < m + 3 * s:
            ma = m + 3 * s
        xscale[elmask] = m
    plt.axvline(1, ls=':', color='C5', label='Equilibrium')
    plt.xlim(mi, ma)
    plt.legend()
    plt.title('Normalized Virial distribution in the sample')
    plt.ylabel('Probability density')
    plt.xlabel('Normalized Virial')
    return xscale
