import marimo

__generated_with = "0.23.16"
app = marimo.App()
#| default_exp vasp_tutorial


@app.cell
def _():
    #| hide
    #| hide
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # VASP Tutorial

    > This example uses VASP to calculate forces and energies. This is a non-free calculator which needs to be installed/setup separately. This example can be easily adapted to some other DFT calculator (e.g. QuantumEspresso, AbInit etc.)
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Setup

    First we need to setup the environment by importing required tools from ASE, stdlib tqdm and hecss libraries.
    """)
    return


@app.cell
def _():
    #| export
    #| export
    from ase.calculators.vasp import Vasp
    from ase import units as un
    from os.path import isfile
    import os

    from hecss import HECSS
    from hecss.util import write_dfset
    from hecss.monitor import plot_stats

    import numpy as np
    from matplotlib import pyplot as plt

    return HECSS, Vasp, np, os, plot_stats, plt, un, write_dfset


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## System setup

    You can run more realistic test using 2x2x2 (or even larger) supercell. The results generated by such calculation are included in the `example/VASP_3C-SiC_calculated` directory in the source tree. You can run post-processing on these results and use them as a reference. By changing the value of the `supercell` variable:
    ```python
    supercell = '2x2x2'
    ```
    you can run a more realistic calculations. If you want to run your own calulation be prepared for some substantial computational resources required for such a job. A single 2x2x2 job takes 2-5 minutes on the 64-core computing node. Better test first with single unit cell setup. For this tutorial we will run with very small system - just a single unit cell of 3C-SiC crystal.
    """)
    return


@app.cell
def _():
    #| export
    #| export
    supercell = '1x1x1'
    return (supercell,)


@app.cell
def _():
    #| export
    #| export
    supercell_1 = '2x2x2'
    return (supercell_1,)


@app.cell
def _():
    #| hide
    #| hide
    supercell_2 = '1x1x1'
    return (supercell_2,)


@app.cell
def _(supercell_2):
    #| export
    #| export
    base_dir = f'example/VASP_3C-SiC/{supercell_2}/'
    return (base_dir,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Calculator setup

    You need to configure your own environment for VASP. The `run-calc` script located in the root directory is an example from my own system. You need to modify it to fit your system.
    Running `run-calc` in a given directory should submit a VASP job to your cluster *and* wait for it to end. Example of such job script from my system (small cluster with SLURM job menager) is included in `example/scripts` directory.
    """)
    return


@app.cell
def _(Vasp, base_dir, supercell_2):
    #| export
    #| export
    calc = Vasp(label='cryst', directory=f'{base_dir}/sc_{supercell_2}/', restart=True)
    cryst = calc.atoms.repeat(1)
    return calc, cryst


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    If you have magmoms in your system you need to use following
    temporary fix for a bug in magmom handling in Vasp2 calculator:
    ```python
    if 'magmom' in calc.list_float_params:
        calc.list_float_params['magmom'] = cryst.get_initial_magnetic_moments()
    ```
    Just copy the above code to a new cell here and execute it.
    """)
    return


@app.cell
def _(calc, cryst, os, supercell_2):
    #| export
    #| export
    calc.set(directory=f'TMP/calc_{supercell_2}/sc')
    calc.set(command=f'{os.getcwd()}/run-calc.sh "3C-SiC-{supercell_2}"')
    calc.set(nsw=0)
    cryst.calc = calc
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## System check

    You should probably check the calculator setup and the stress tensor of the supercell to make sure it is in equilibrium before running long sequence of DFT calculations. Here is an example:
    """)
    return


@app.cell
def _(calc, un):
    #| export
    #| export
    print('Stress tensor: ', end='')
    for ss in calc.get_stress()/un.GPa:
        print(f'{ss:.3f}', end=' ')
    print('GPa')
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Running HECSS

    There are multiple ways you can use HECSS to generate samples -- depending from the stage your project is, your familiarity with python language and sophistication required by your project.

    You would probably start with more exploratory setup when you start the project and do not know yet the behaviour of the system. It is best to start with small structure, small initial number of samples and code structure which allows for iterating by returning to the same calculation to generate more samples or breaking the loop which goes wrong. This type of calculation may be well served by the code like the following example:
    """)
    return


@app.cell
def _(supercell_2):
    #| export
    #| export
    xsl = []
    calc_dir = f'TMP/calc_{supercell_2}'
    return (calc_dir,)


@app.cell
def _(HECSS, calc, calc_dir, cryst):
    #| export
    #| export
    hecss = HECSS(cryst, calc,
                  directory=f'{calc_dir}',
                  w_search=True,
                  pbar=True)
    return (hecss,)


@app.cell
def _(hecss, np, plt, un):
    #| export
    #| export
    m, s, xscl = hecss.estimate_width_scale(10, nwork=0)
    wm = np.array(hecss._eta_list).T
    y = np.sqrt((3*wm[1]*un.kB)/(2*wm[2]))
    plt.plot(wm[1], y, '.');
    x = np.linspace(0, 1.05*wm[1].max(), 2)
    fit = np.polyfit(wm[1], y, 1)
    plt.plot(x, np.polyval(fit, x), ':', label=f'{fit[1]:.4g} {fit[0]:+.4g} T')
    plt.axhline(m, ls='--', label=f'{m:.4g}±{s:.4g}')
    plt.axhspan(m-s, m+s, alpha=0.3)
    plt.ylim(m-4*s, m+4*s)
    plt.xlabel('Target temperature (K)')
    plt.ylabel('width scale ($\\AA/\\sqrt{K}$)')
    plt.legend();
    return


@app.cell
def _():
    #| export
    #| export
    T = 300
    return (T,)


@app.cell
def _():
    N = 4
    return (N,)


@app.cell
def _(N, T, hecss):
    #| export
    #| export
    samples = hecss.sample(T, N)
    return (samples,)


@app.cell
def _(T, hecss, plot_stats, samples):
    #| export
    #| export
    plot_stats(samples, T)
    distrib = hecss.generate(samples, T)
    plot_stats(distrib, T, sqrN=True)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    After the first run you can increase the limit (N) and return to the same loop (the state of the sampler is preserved) to generate more samples. This cell can be executed multiple times to collect enough samples for further analysis. You can also monitor the progress by providing `sentinel` argument to the `generate` method. Here is a simple monitoring function showing an updated histogram and position of the last sample (as dotted line)
    """)
    return


@app.cell
def _(plot_stats):
    #| export
    #| export
    def show_stats(s, sl, col=None, Temp=None):
        from matplotlib import pyplot as plt
        from IPython.display import clear_output
        from hecss.optimize import make_sampling
        plot_stats(make_sampling(sl if col is None else col + sl, Temp),
                   Temp, show=False)
        plt.axvline(s[-1], ls=':', label='Last sample')
        plt.legend()
        plt.show()
        clear_output(wait=True)
        return False

    return (show_stats,)


@app.cell
def _(T, hecss, plot_stats, samples, show_stats):
    #| export
    #| export
    N_1 = 10
    samples_1 = samples + hecss.sample(T, N_1, sentinel=show_stats, sentinel_args={'col': samples, 'Temp': T})
    plot_stats(hecss.generate(samples_1, T), T, sqrN=True)
    return N_1, samples_1


@app.cell
def _(N_1, T, hecss, samples_1, show_stats):
    #| export
    #| export
    samples_2 = samples_1 + hecss.sample(T, N_1, sentinel=show_stats, sentinel_args={'col': samples_1, 'Temp': T})
    return (samples_2,)


@app.cell
def _(T, hecss, plot_stats, samples_2):
    #| export
    #| export
    plot_stats(hecss.generate(samples_2, T), T, sqrN=True)
    return


@app.cell
def _(T, calc_dir, samples_2, write_dfset):
    #| export
    #| export
    for c in samples_2:
        write_dfset(f'{calc_dir}/DFSET_T={T}K.dat', c)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    When you are at production stage of your project and you know exactly what you want and how to get it the more compact style of code may be better. Though, it is less elastic and forgiving of mistakes. Here is a similar sampling run at T=600 K.
    """)
    return


@app.cell
def _(hecss, plot_stats):
    #| export
    #| export
    T_1 = 600
    confs_600 = hecss.sample(T_1, 50)
    plot_stats(hecss.generate(confs_600, T_1), T_1, sqrN=True)
    return T_1, confs_600


@app.cell
def _(T_1, calc_dir, confs_600, write_dfset):
    #| export
    #| export
    for c_1 in confs_600:
        write_dfset(f'{calc_dir}/DFSET_T={T_1}K.dat', c_1)
    return


@app.cell
def _(T_1, confs_600, hecss):
    #| export
    #| export
    hecss.generate(confs_600, T_1, debug=True)
    return


@app.cell
def _(hecss):
    #| export
    #| export
    c_1000 = hecss.sample(1000, 50)
    return (c_1000,)


@app.cell
def _(c_1000, np):
    #| export
    #| export
    T_1000 = np.array([s[-1] for s in c_1000]).mean()
    return (T_1000,)


@app.cell
def _(T_1000, c_1000, hecss, un):
    #| export
    #| export
    s_1000 = hecss.generate(c_1000, 2*T_1000/un.kB/3, border=True, debug=True)
    return (s_1000,)


@app.cell
def _(calc_dir, s_1000, write_dfset):
    #| export
    #| export
    for c_2 in s_1000:
        write_dfset(f'{calc_dir}/DFSET_T={1000}K.dat', c_2)
    return


if __name__ == "__main__":
    app.run()