import marimo

__generated_with = "0.23.16"
app = marimo.App()


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Temperature scan planner
    """)
    return


@app.cell
def _():
    from ase.build import bulk
    import ase.units as un
    from scipy import stats
    from matplotlib import pylab as plt
    import numpy as np
    import itertools
    from tqdm.auto import tqdm
    return bulk, itertools, np, plt, stats, tqdm, un


@app.cell
def _(itertools):
    flatten = itertools.chain.from_iterable
    return (flatten,)


@app.cell
def _(np, plt, stats):
    def plan_T_scan(Tlo, Thi, nat, N=1, plot_dist=True):
        l = Tlo
        n = np.sqrt(3 * nat / 2 / 2)  # 1/sqrt(2) adjusts for the shape of the distribution 
        s0 = l / n  # generated by the HECSS.smple function.
        s = s0
        assert n > 1
        a = (n + 1) / (n - 1)
        r = []
        while l <= Thi:
            sf = s
            if l * a > Thi:
                sf = sf * 1.12
            r.append([l, s, sf / s0])
            l = l * a
            s = l / n
        ns = 1
        frm = 'N=%.1f'
        if N > 1:
            ns = N / r[-1][-1]
            frm = 'N=%.0f'
            r = [[l, s, int(round(ns * sf))] for l, s, sf in r]
        frm = frm + ' T=%.0fK'
        if plot_dist:
            f = stats.norm.pdf
            x = np.linspace(Tlo * (1 - 3 / n), Thi * (1 + 3 / n), 600)
            y = np.zeros(x.shape)
            for c, (l, s, sf) in enumerate(r):
                p = sf * f(x, l, s)
                plt.plot(x, p, label=frm % (sf, l))
                y = y + p
            plt.plot(x, y)
            plt.legend(loc='upper right')
            plt.xlabel('Temperature')
            plt.ylabel('Relative density')
            plt.title('Temperature scan. N=relative number of samples')
        return r

    return (plan_T_scan,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Simulate with `stats.normal` random variable
    """)
    return


@app.cell
def _(np, plan_T_scan, plt, stats, tqdm):
    plt.figure(figsize=(10, 6))
    rv = stats.norm
    N = 100_000
    plan = plan_T_scan(50, 250, 32, N)

    el = np.zeros(0)
    for c, (l, s, n) in enumerate(tqdm(plan)):
        el = np.append(el, rv.rvs(loc=l, scale=s, size=n))

    skip = len(el) // 2000
    skip = int(max(1, skip))
    for s in el[::skip]:
        plt.axvline(s, ymin=0.95, ymax=0.98, ls='-', color='r', alpha=0.1)

    NF = sum([sf for _, _, sf in plan])
    counts, bins = np.histogram(el, bins='auto', density=True)
    plt.hist(bins[:-1], bins, weights=NF * counts, color='C0', alpha=0.3)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Run with `HECSS` sampler
    """)
    return


@app.cell
def _():
    from hecss.core import HECSS
    from hecss.util import select_asap_model, create_asap_calculator
    from hecss.optimize import make_sampling
    from hecss.monitor import plot_stats

    return (
        HECSS,
        create_asap_calculator,
        make_sampling,
        plot_stats,
        select_asap_model,
    )


@app.cell
def _(HECSS, bulk, create_asap_calculator, select_asap_model):
    model = select_asap_model('SiC')
    print(f'Using potential model: {model}')

    sys_size = '3x3x3'
    sc = [int(v) for v in sys_size.split('x')]

    cryst = bulk('SiC', crystalstructure='zincblende',
                     a=4.38120844, cubic=True).repeat(tuple(sc))
    cryst.calc = create_asap_calculator(model)
    hecss = HECSS(cryst, lambda: create_asap_calculator(model), pbar=False)
    hecss.estimate_width_scale(10, Tmax=1000)
    return cryst, hecss


@app.cell
def _(cryst, plan_T_scan, plt):
    N_1 = 1000
    plt.figure(figsize=(10, 6))
    plan_1 = plan_T_scan(150, 250, len(cryst), N_1)
    return N_1, plan_1


@app.cell
def _(hecss, np, plan_1, tqdm):
    smpls = {}
    for T, sig, n_1 in tqdm(plan_1):
        smpls[T] = np.array([s[-1] for s in hecss._sampler_ser(T, n_1)])
    return (smpls,)


@app.cell
def _(np, smpls):
    ell = np.concatenate(list(smpls.values()))
    e_min = ell.min()
    e_max = ell.max()
    return e_max, e_min, ell


@app.cell
def _(e_max, e_min, ell, plt, smpls):
    for T_1, el_1 in smpls.items():
        plt.hist(el_1, bins=50, histtype='step', label=f'T={T_1:.0f}K', range=(e_min, e_max))
    plt.hist(ell, bins=50, stacked=True, color='C0', alpha=0.25, range=(e_min, e_max))
    plt.legend()
    return


@app.cell
def _(N_1, e_max, e_min, ell, np, plan_1, plt, smpls, stats, un):
    plt.figure(figsize=(10, 6))
    if N_1 < 10000:
        bins_1 = np.linspace(e_min, e_max, 50) * 2 / un.kB / 3
    else:
        bins_1 = 'auto'
    cnt, bins_1, _ = plt.hist(ell * 2 / un.kB / 3, bins=bins_1, density=False, alpha=0.6, label='Total')
    x = np.linspace(bins_1[0], bins_1[-1], 300)
    y = np.zeros(x.shape)
    tdx = bins_1[1] - bins_1[0]
    for c_1, ((T_2, el_2), (Tp, sig_1, n_2)) in enumerate(zip(smpls.items(), plan_1)):
        e = el_2 * 2 / un.kB / 3
        Tc, Tb, _ = plt.hist(e, bins=bins_1, density=False, histtype='step', color=f'C{c_1 + 1}')
        dx = Tb[1] - Tb[0]
        fit = stats.norm.fit(e)
        plt.plot(x, dx * n_2 * stats.norm.pdf(x, *fit), color=f'C{c_1 + 1}', label=f'T={T_2:.1f}K (N={int(Tc.sum())})')
        y = y + tdx * n_2 * stats.norm.pdf(x, *fit)
        skip_1 = len(el_2) // 500
        skip_1 = max(1, skip_1)
        for v in e[::skip_1]:
            plt.axvline(v, ymin=0.95, ymax=0.98, ls='-', color='r', alpha=0.05)
    plt.plot(x, y, '--', label='Total')
    plt.xlabel('Temperature (K)')
    plt.legend(loc='upper right')
    plt.title('Temperature scan - HECSS generated energies.')
    plt.grid()
    plt.savefig(f'AUX/T_scan_N={N_1!r}.pdf')
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Test temperature scanning planner
    """)
    return


@app.cell
def _(cryst, plan_T_scan, plt):
    N_2 = 1000
    plt.figure(figsize=(8, 4))
    plan_2 = plan_T_scan(200, 400, len(cryst), N_2)
    plt.savefig('AUX/T_scan_plan.pdf', bbox_inches='tight')
    return N_2, plan_2


@app.cell
def _(hecss, plan_2, tqdm):
    smpll = []
    for T_3, sig_2, n_3 in tqdm(plan_2):
        smpll.append([s for s in hecss.sample(T_3, n_3)])
    ell_1 = [[s[-1] for s in sl] for sl in smpll]
    return ell_1, smpll


@app.cell
def _(smpll):
    usmp = []
    for sl in smpll:
        usmp = usmp + sl
    return (usmp,)


@app.cell
def _(plt, usmp):
    plt.figure(figsize=(8, 4))
    plt.hist([s[-1] for s in usmp], bins='auto', density=True)
    plt.xlabel('Potential energy (meV/at)')
    plt.ylabel('Probability density (meV/at)$^{-1}$')
    plt.title('Temperatures: 200-400K')
    plt.savefig(f'AUX/uniform.pdf', bbox_inches='tight')
    return


@app.cell
def _(N_2, make_sampling, plot_stats, plt, usmp):
    T_4 = 273
    wd = make_sampling(usmp, T_4, N=4 * N_2, nonzero_w=False, debug=True)
    print(len(usmp), len(wd))
    plt.legend(loc='upper right', bbox_to_anchor=(1.0, 0.95))
    plt.show()
    plot_stats(wd, T_4, sqrN=True, show=False)
    plt.savefig(f'AUX/T_scan_T={T_4:.0f}K.pdf', bbox_inches='tight')
    return


@app.cell
def _(N_2, ell_1, flatten, np, plan_2, plt, stats, un):
    plt.figure(figsize=(10, 6))
    if N_2 < 1000:
        bins_2 = np.linspace(min(flatten(ell_1)), max(flatten(ell_1)), 40) * 2 / un.kB / 3
    else:
        bins_2 = 'auto'
    cnt_1, bins_2, _ = plt.hist(np.array(list(flatten(ell_1))) * 2 / un.kB / 3, bins=50, density=False, alpha=0.3, label='Total')
    x_1 = np.linspace(bins_2[0], bins_2[-1], 300)
    y_1 = np.zeros(x_1.shape)
    tdx_1 = bins_2[1] - bins_2[0]
    for c_2, (el_3, (T_5, sig_3, n_4)) in enumerate(zip(ell_1, plan_2)):
        e_1 = np.array(el_3)
        bins_2 = 'auto'
        Tc_1, Tb_1, _ = plt.hist(e_1 * 2 / un.kB / 3, bins=bins_2, density=False, histtype='step', color=f'C{c_2 + 1}')
        dx_1 = Tb_1[1] - Tb_1[0]
        nf = np.sum(Tc_1) * dx_1
        fit_1 = stats.logistic.fit(e_1 * 2 / un.kB / 3)
        plt.plot(x_1, nf * stats.logistic.pdf(x_1, *fit_1), color=f'C{c_2 + 1}', label=f'T={T_5:.1f}K (N={int(Tc_1.sum())})')
        y_1 = y_1 + nf * stats.logistic.pdf(x_1, *fit_1)
        skip_2 = len(el_3) // 1000
        skip_2 = max(1, skip_2)
        for v_1 in e_1[::skip_2] * 2 / un.kB / 3:
            plt.axvline(v_1, ymin=0.95, ymax=0.98, ls='-', color='r', alpha=0.05)
    plt.plot(x_1, y_1, '--', label='Plan (total)')
    plt.xlabel('Temperature (K)')
    plt.legend(loc='upper right')
    plt.title('Temperature scan - HECSS generated energies.')
    plt.grid()
    plt.savefig(f'AUX/T_scan_N={N_2!r}.pdf')
    return


@app.cell
def _(np, plt, stats):
    x_2 = np.linspace(-5, 5, 100)
    plt.plot(x_2, stats.norm.pdf(x_2))
    plt.grid()
    plt.axhline(1 / 8)
    plt.axvline(np.log(3 + 2 * np.sqrt(2)))
    plt.axvline(np.log(3 - 2 * np.sqrt(2)))
    plt.plot(x_2, stats.logistic.pdf(x_2))
    s_1 = 2
    plt.plot(x_2, stats.logistic.pdf(x_2, scale=s_1))
    plt.axhline(1 / (8 * s_1))
    plt.axvline(s_1 * np.log(3 + 2 * np.sqrt(2)))
    plt.axvline(s_1 * np.log(3 - 2 * np.sqrt(2)))
    return


@app.cell
def _(np, plt, stats):
    x_3 = np.linspace(0, 15, 300)
    y_2 = np.zeros(x_3.shape)
    a = np.log(3 + 2 * np.sqrt(2))
    a = 1.4
    x0 = 3
    b = 1 / 8
    nf_1 = 1
    while x0 < 15:
        s_2 = x0 * b
        if x0 * (1 + b * a) / (1 - b * a) > 15:
            nf_1 = 1.3
            x0 = x0 * 1.05
        yy = nf_1 * s_2 * stats.logistic.pdf(x_3, loc=x0, scale=s_2)
        plt.plot(x_3, yy)
        y_2 = y_2 + yy
        x0 = x0 * ((1 + a * b) / (1 - a * b))
    plt.plot(x_3, y_2)
    plt.axhline(1 / 4)
    plt.axhline(1 / 8)
    return


@app.cell
def _(np, plan_T_scan, plt, stats, tqdm):
    plt.figure(figsize=(10, 6))
    rv_1 = stats.norm
    N_3 = 1000000
    plan_3 = plan_T_scan(50, 250, 32, N_3)
    el_4 = np.zeros(0)
    for c_3, (l_1, s_3, n_5) in enumerate(tqdm(plan_3)):
        el_4 = np.append(el_4, rv_1.rvs(loc=l_1, scale=s_3, size=n_5))
    skip_3 = len(el_4) // 2000
    skip_3 = int(max(1, skip_3))
    for s_3 in el_4[::skip_3]:
        plt.axvline(s_3, ymin=0.95, ymax=0.98, ls='-', color='r', alpha=0.1)
    NF_1 = sum([sf for _, _, sf in plan_3])
    counts_1, bins_3 = np.histogram(el_4, bins='auto', density=True)
    plt.hist(bins_3[:-1], bins_3, weights=NF_1 * counts_1, color='C0', alpha=0.3)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Scanning with width instead of temperature
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Uniform distribution
    """)
    return


if __name__ == "__main__":
    app.run()