import marimo

__generated_with = "0.23.16"
app = marimo.App()


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Amplitude correction extraction

    > This module provides a way to extract amplitude correction matrix from the eta calculation data generated by the `estimate_width_scale` method.
    """)
    return


@app.cell
def _():
    from hecss import HECSS
    from hecss.util import normalize_conf, get_cell_data
    from hecss.monitor import plot_hist
    return HECSS, get_cell_data, normalize_conf, plot_hist


@app.cell
def _():
    import numpy as np
    from scipy.special import expit
    from scipy.stats import chi2, chi, norm

    import ase
    import ase.units as un
    from ase.calculators.vasp import Vasp
    import spglib
    from spglib import find_primitive, get_symmetry_dataset
    from glob import glob
    from matplotlib import pyplot as plt

    return ase, chi, get_symmetry_dataset, glob, norm, np, plt, spglib, un


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## LAMPS data on olivine
    """)
    return


@app.cell
def _(np, plot_hist, plt):
    def plot_virial_stat(cryst, smpl, normal=True):
        elems = cryst.get_chemical_symbols()
        elmap = cryst.get_atomic_numbers()
        vir = np.array([abs(s[2] * s[3]) for s in smpl])
        vir = vir / vir.mean(axis=(-1, -2))[:, None, None]
        nat = len(elems)
        xscale = np.ones(cryst.get_positions().shape)
        mi = 1
        ma = 1
        for n, el in enumerate(sorted(set(elems))):
            elmask = np.array(elems) == el
            m, s = plot_hist(1 / np.sqrt(vir[:, elmask, :].mean(axis=(-1, -2))), el, n + 1, normal=normal, df=3 * sum(elmask))
            if mi > m - 3 * s:
                mi = m - 3 * s
            if ma < m + 3 * s:
                ma = m + 3 * s
            xscale[elmask] = m
        plt.axvline(1, ls=':', color='C5', label='Equilibrium')
        plt.xlim(mi, ma)
        plt.legend()
        plt.title('Normalized Virial distribution in the sample')
        plt.ylabel('Probability density')
        plt.xlabel('Normalized Virial')
        return xscale

    return (plot_virial_stat,)


@app.cell
def _():
    from hecss.monitor import plot_stats, plot_xs_stat
    from hecss.monitor import plot_acceptance_history, plot_dofmu_stat
    from hecss.util import select_asap_model, create_asap_calculator
    from hecss.util import calc_init_xscale
    from tqdm.auto import tqdm

    return (
        create_asap_calculator,
        plot_dofmu_stat,
        plot_xs_stat,
        select_asap_model,
    )


@app.cell
def _(ase, create_asap_calculator, get_cell_data, select_asap_model, spglib):
    model = select_asap_model('Universal')
    print(f'Using potential model: {model}')

    oliv = ase.io.read('data/spinel.POSCAR')
    oliv.calc = create_asap_calculator(model)
    print(f'Space group: {spglib.get_spacegroup(get_cell_data(oliv))}')
    return model, oliv


@app.cell
def _(HECSS, create_asap_calculator, model, oliv):
    N = 100

    sampler = HECSS(oliv, lambda: create_asap_calculator(model))
    m, s, xscl = sampler.estimate_width_scale(N, Tmax=1000)
    return sampler, xscl


@app.cell
def _(np, oliv, plot_hist, plt, sampler, un):
    wm = np.array(sampler._eta_list).T
    y = np.sqrt((3 * wm[1] * un.kB) / (2 * wm[2]))
    plot_hist(y, '', 0, normal=False, df=3 * len(oliv))
    plt.legend()
    plt.show()
    return


@app.cell
def _(oliv, plot_virial_stat, plt, sampler):
    plt.semilogx()
    plot_virial_stat(oliv, sampler._eta_samples, normal=False)
    return


@app.cell
def _(sampler, xscl):
    T = 600
    N_1 = 1000
    dofmu = []
    xsl = []
    sampler.xscale_init = xscl.copy()
    osamples = sampler.sample(T, N_1, dofmu_list=dofmu, xscale_list=xsl)
    return dofmu, osamples, xsl


@app.cell
def _(oliv, osamples, plot_virial_stat):
    plot_virial_stat(oliv, osamples, normal=False)
    return


@app.cell
def _(dofmu, oliv, plot_dofmu_stat):
    plot_dofmu_stat(oliv, dofmu, skip=0, window=10)
    return


@app.cell
def _(oliv, plot_xs_stat, xsl):
    plot_xs_stat(oliv, xsl, skip=0, window=10)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## VASP calculations

    > Here we use pre-calculated vasp data for 3C-SiC 2x2x2 supercell
    """)
    return


@app.cell
def _():
    supercell = '2x2x2'
    return (supercell,)


@app.cell
def _(ase, supercell):
    sc = ase.io.read(f'example/VASP_3C-SiC/{supercell}/sc_{supercell}/vasprun.xml')
    return (sc,)


@app.cell
def _(sc):
    e0 = sc.get_potential_energy()
    return (e0,)


@app.cell
def _(get_cell_data, get_symmetry_dataset, np, sc):
    eqdelta = 0.05
    eqsigma = 0.2
    nat = len(sc)
    dim = (nat, 3)
    symprec = 1e-5
    symm = get_symmetry_dataset(get_cell_data(sc), symprec=symprec)
    dofmap = symm.mapping_to_primitive
    dof = list(sorted(set(dofmap)))
    dofmu_1 = np.ones((len(dof), 3))
    mu = np.ones(dim)
    return dim, dof, dofmap, nat


@app.cell
def _(ase, dim, dof, dofmap, e0, glob, nat, normalize_conf, np, sc, supercell):
    xscale = np.ones(dim)
    dofxs = np.array([xscale[dofmap == d, :].mean(axis=0) for d in dof])
    vt = []
    for i, sfn in enumerate(sorted(glob(f'example/VASP_3C-SiC_calculated/calc_{supercell}/w_est/*/vasprun.xml'))):
        s_1 = ase.io.read(sfn)
        dx = normalize_conf(s_1, sc)[0] - sc.get_positions()
        try:
            f = s_1.get_forces()
            e = (s_1.get_potential_energy() - e0) / nat
            v = np.abs(dx * f)
            v = dx * f
            v = v / v.mean()
            dofv = np.array([v[dofmap == d, :].mean(axis=0) for d in dof])
            vt.append(dofv.reshape(-1))
        except RuntimeError:
            continue
    vt = np.array(vt).reshape(-1, 2, 3)
    vta = vt.reshape(-1, 2, 3).mean(axis=-1)
    mu_1 = vta.cumsum(axis=0)
    mu_1 = mu_1 / np.arange(1, len(mu_1) + 1)[:, None]
    return mu_1, vt, vta


@app.cell
def _(mu_1, plt, vta):
    plt.plot(mu_1, '-')
    plt.plot(vta, '.', ms=1)
    for dofn in (0, 1):
        m_1 = vta[:, dofn].mean()
        s_2 = vta[:, dofn].std()
        plt.axhline(m_1, ls=':', color=f'C{dofn}')
        plt.axhspan(m_1 - s_2, m_1 + s_2, color=f'C{dofn}', alpha=0.2)
    mu_1[-1]
    return


@app.cell
def _(chi, norm, np, plt, vt):
    x = np.linspace(0.5, 1.5, 100)
    for dofn_1 in (0, 1):
        rv = vt[:, dofn_1, :].mean(axis=-1).reshape(-1)
        plt.hist(rv, density=True, bins='auto', color=f'C{dofn_1}', alpha=0.33, label=f'{dofn_1}')
        fit = chi.fit(rv, f0=12)
        plt.plot(x, chi.pdf(x, *fit), ls=':', color=f'C{dofn_1}')
        fit = norm.fit(rv)
        plt.plot(x, norm.pdf(x, *fit), ls='-', color=f'C{dofn_1}')
    return


if __name__ == "__main__":
    app.run()