name: ASAP tests
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ../../asap_env.yaml
          environment-name: asap_env

      # Linux and macOS
      - name: Run Python
        shell: bash -l {0}
        run: |
          nbdev_test --do_print

 
